kind: Service
apiVersion: v1
metadata:
  name: spring-web-example-service
spec:
  type: NodePort
  selector:
    app: spring-web-example
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-web-example-deployment
  labels:
    app: spring-web-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-web-example
  template:
    metadata:
      labels:
        app: spring-web-example
    spec:
      containers:
      - name: spring-web-example
        image: micsnbricks/cool-spring-app:latest
        ports:
        - containerPort: 8080
